{
 "title": "PL Market Value API Observability",
 "tags": [
  "mlops",
  "fastapi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Second by Handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Request Latency P95 (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "p95 - {{handler}}"
    }
   ]
  },
  {
   "title": "Total Processed Predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=~\"/predict.*\"})",
     "legendFormat": "Predictions"
    }
   ]
  }
 ]
}